### ISSUE TITLE
Error: New route X conflicts with existing Y

### ISSUE THREAD

**Issue by krnlde** [micromata/http-fake-backend#1]
```
{
        {
            params: '/{id}/note/{noteId}',
            method: 'PUT'
        },
        {
            params: '/{id}/note/{noteId}',
            method: 'PATCH'
        }
}
```

This should work since there are different methods to the same endpoint, but it fails with the following message: `Error: New route /api/salesItem/{id}/note/{noteId} conflicts with existing /api/salesItem/{id}/note/{noteId}`

**Comment by mischah** [comment]
Yeah. Right. I loop through the `urls` array to create server routes. So that can’t work.

But I see the need to have multiple methods for but I would prefer the following approach.

Instead of:

```javascript
urls: [
  {
    params: '/{id}/note/{noteId}',
    response: '/json-templates/foo.json',
    method: 'PUT'
  },
  {
    params: '/{id}/note/{noteId}',
    response: '/json-templates/foo.json',
    method: 'PATCH'
  }
]
```

I would define this route via 

```javascript
urls: [
  {
    params: '/{id}/note/{noteId}',
    response: '/json-templates/foo.json',
    methods: ['PUT', 'PATCH']
  }
]
```

Feedback appreciated @krnlde @revrng

**Comment by krnlde** [comment]
What if I need another response for PUT than for PATCH?

**Comment by mischah** [comment]
See above :arrow_up:

**Comment by krnlde** [comment]
D'accord

**Comment by mischah** [comment]
The question is which of the two approaches is less ugly :neckbeard: 

I guess I would prefer the latter one.
The first one might be more readable. But I hate to misuse keys (eg. `PUT`) as values.

**Comment by krnlde** [comment]
The latter is the better for me. I think you can  also omit the `success: true` part for convenience. It should be treated the same way (implicit 200 OK)

**Comment by mischah** [comment]
The `{ success: true }` thingie ist just an example for returning a JavaScript object instead of the content of a JSON file.

This is an already existing feature. See [README](https://github.com/micromata/http-fake-backend#example-configuration) or [tests](https://github.com/micromata/http-fake-backend/blob/master/test/server/api/endpoint.js#L13-L38) :smirk:

**Comment by krnlde** [comment]
Cooool. I'm new, so sorry for being stupid :)

**Comment by mischah** [comment]
Haha. My pleasure :laughing:
