### ISSUE TITLE
Only getting response for GET Method

### ISSUE THREAD

**Issue by kaustavbasu075** [micromata/http-fake-backend#20]
I am not able to get a response for a PUT method.I get the below
{"statusCode":405,"error":"Method Not Allowed","message":"Method Not Allowed"}
I get this for the default put example provided too.Could you please help me out with this.I might be missing something.

**Comment by krnlde** [comment]
Did you do it as described in the [advanced example](https://github.com/micromata/http-fake-backend#advanced-example)?

**Comment by mischah** [comment]
Can’t reproduce this with `8.9.1`.

This works:

https://github.com/micromata/http-fake-backend/blob/6f77e92e0ec6b8019a1118202d5eef097af1ac5a/server/api/anotherExample.js#L1-L27

As well as 

```javascript
'use strict';

const SetupEndpoint = require('./setup/');

module.exports = SetupEndpoint({
    name: 'simpleExample',
    urls: [{
        requests: [
            {
                method: 'PUT',
                response: '/response-files/simpleExample.json'
            }
        ]
    }]
});
```

Sorry, I currently have no idea what you might be missing.
