### ISSUE TITLE
Respond with HTML

### ISSUE THREAD

**Issue by Anbe93** [micromata/http-fake-backend#9]
I would love to have the possibility to get a HTML from the fake-backend.
@krnlde told me he implemented this feature 'inofficial' already.

**Comment by krnlde** [comment]
I implemented the feature to respond with an arbritary file and mime type in a project. I need to dig into the code again to find the patch.

**Comment by mischah** [comment]
Duplicates #7

**Comment by mischah** [comment]
Hope to finde some time to implement that next week. 😘
